// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "af.h"

void emAfInit(void);

void emAfTick(void);

void emAfResetAttributes(uint8_t endpointId);

bool emAfPreCommandReceived(EmberAfClusterCommand* cmd);

bool emAfPreZDOMessageReceived(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length);
