@echo off

REM This file was generated by Simplicity Studio from the following template:
REM   app/esf_common/template/efr32/efr32-postbuild-afv2.bat
REM Please do not edit it directly.

REM Post Build processing for IAR Workbench.

REM Turn on delayed expansion
setlocal enabledelayedexpansion enableextensions

SET TARGET_BPATH=%1%
SET PROJECT_DIR=%2%
SET PROJECT_DIR=%PROJECT_DIR:"=%

REM Extracting the current directory
SET CURRENT_DIR=%cd:Z:=%
SET CURRENT_DIR=%CURRENT_DIR:\=/%

REM Extracting the path to s37 for iar and studio
SET TARGET_BPATH=%TARGET_BPATH:Z:=%
SET TARGET_BPATH=%TARGET_BPATH:\=/%
IF EXIST "%CURRENT_DIR%/%TARGET_BPATH%.s37" (
  SET TARGET_BPATH=%CURRENT_DIR%/%TARGET_BPATH%
)

SET ARCHITECTURE_SERIES=1
SET ARCHITECTURE_CONFIGURATION=1

IF [%ARCHITECTURE_SERIES%] GEQ [2] (
  GOTO GBL
)
IF [%ARCHITECTURE_CONFIGURATION%] GEQ [2] (
  GOTO GBL
)
GOTO EBL

:EBL
  SET CONVERT_FLAGS=Z:
  SET CONVERT_FLAGS=%CONVERT_FLAGS:Z:=%
  IF [""] == [""] (
	  SET EBL_FILE=%TARGET_BPATH%.ebl
  ) ELSE (
	  SET CONVERT_FLAGS=%CONVERT_FLAGS:\=/%
	  SET EBL_FILE=%TARGET_BPATH%.ebl.encrypted
  )
  echo " "
  echo "This converts S37 to Ember Bootload File format if a bootloader has been selected in AppBuilder"
  echo " "
  @echo on
  cmd /C ""C:\SiliconLabs\SimplicityStudio\v4\developer\adapter_packs\commander\commander.exe" ebl create "%EBL_FILE%" --app "%TARGET_BPATH%.s37" --device EFR32MG1P132F256GM48 %CONVERT_FLAGS% > "%TARGET_BPATH%-commander-convert-output-ebl.txt""
  @echo off
  type "%TARGET_BPATH%-commander-convert-output-ebl.txt"
  GOTO Done

:GBL
  echo " "
  echo "This converts S37 to Gecko Bootload File format if a bootloader has been selected in AppBuilder"
  echo " "
  @echo on
  cmd /C ""C:\SiliconLabs\SimplicityStudio\v4\developer\adapter_packs\commander\commander.exe" gbl create "%TARGET_BPATH%.gbl" --app "%TARGET_BPATH%.s37" --device EFR32MG1P132F256GM48 > "%TARGET_BPATH%-commander-convert-output-gbl.txt""
  @echo off
  type "%TARGET_BPATH%-commander-convert-output-gbl.txt"
  GOTO Done

:Done
  echo " "
  echo "This creates a ZigBee OTA file if the "OTA Client Policy Plugin" has been enabled."
  echo "It uses the parameters defined there.  "
  echo " "
  @echo on
  cmd /C ""%PROJECT_DIR%\..\..\..\protocol\zigbee_5.9\tool\image-builder\image-builder-windows.exe" --create "%TARGET_BPATH%.ota" --version 1 --manuf-id 0x0 --image-type 0 --tag-id 0x0000 --tag-file "%TARGET_BPATH%.ebl" --string "EBL ZigbeeSW"" > "%TARGET_BPATH%-image-builder-output.txt"
  @echo off
  type "%TARGET_BPATH%-image-builder-output.txt"
  @echo on
